public class TrainController extends javax.swing.JFrame {
	
	TrainView tv;
	
    public TrainController(int ID) {
		
		tv = new TrainView(ID);
		
		try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
		initComponents();
		
        //</editor-fold>
        // /* Create and display the form */
        // java.awt.EventQueue.invokeLater(new Runnable() {
            // public void run() {
                // new TrainController().setVisible(true);
            // }
        // });
    }
	
	public void update(){
		tv.update();
		
		powReqFld.setText(Integer.toString(tv.tm.powReq));
        	setSpdFld.setText(Integer.toString(tv.tm.setpnt));
        	curSpdFld.setText(Integer.toString(tv.tm.curSpd));
        	authFld.setText(Integer.toString(tv.tm.authority));
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Lights = new javax.swing.ButtonGroup();
        AC = new javax.swing.ButtonGroup();
        Heater = new javax.swing.ButtonGroup();
        LeftDoors = new javax.swing.ButtonGroup();
        RightDoors = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        leftDoorOpenButton = new javax.swing.JRadioButton();
        rightDoorOpenButton = new javax.swing.JRadioButton();
        heaterOffButton = new javax.swing.JRadioButton();
        leftDoorClosedButton = new javax.swing.JRadioButton();
        rightDoorClosedButton = new javax.swing.JRadioButton();
        heaterOnButton = new javax.swing.JRadioButton();
        acOnButton = new javax.swing.JRadioButton();
        lightsOnButton = new javax.swing.JRadioButton();
        acOffButton = new javax.swing.JRadioButton();
        lightsOffButton = new javax.swing.JRadioButton();
        leftDoorFailButton = new javax.swing.JRadioButton();
        acFailButton = new javax.swing.JRadioButton();
        heaterFailButton = new javax.swing.JRadioButton();
        rightDoorFailButton = new javax.swing.JRadioButton();
        lightsFailButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adButton = new javax.swing.JToggleButton();
        autoButton = new javax.swing.JToggleButton();
        vParamButton = new javax.swing.JButton();
        trainIDFld = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        setSpdFld = new javax.swing.JTextField();
        authFld = new javax.swing.JTextField();
        curSpdFld = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        psngrBrkButton = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        pwrReqFld = new javax.swing.JTextField();
        spdReqFld = new javax.swing.JTextField();
        eBrkButton = new javax.swing.JToggleButton();
        srvBrkButton = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Train Controller - Blue Team");
        setPreferredSize(new java.awt.Dimension(1028, 500));

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(47, 47, 47))
        );

        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        LeftDoors.add(leftDoorOpenButton);
        leftDoorOpenButton.setText("Open");
        leftDoorOpenButton.setContentAreaFilled(false);
        leftDoorOpenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leftDoorOpenButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        leftDoorOpenButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        leftDoorOpenButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        leftDoorOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDoorOpenButtonActionPerformed(evt);
            }
        });

        RightDoors.add(rightDoorOpenButton);
        rightDoorOpenButton.setText("Open");
        rightDoorOpenButton.setContentAreaFilled(false);
        rightDoorOpenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rightDoorOpenButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rightDoorOpenButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        rightDoorOpenButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rightDoorOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightDoorOpenButtonActionPerformed(evt);
            }
        });

        Heater.add(heaterOffButton);
        heaterOffButton.setSelected(true);
        heaterOffButton.setText(" Off  ");
        heaterOffButton.setContentAreaFilled(false);
        heaterOffButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        heaterOffButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        heaterOffButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        heaterOffButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        heaterOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heaterOffButtonActionPerformed(evt);
            }
        });

        LeftDoors.add(leftDoorClosedButton);
        leftDoorClosedButton.setSelected(true);
        leftDoorClosedButton.setText("Closed");
        leftDoorClosedButton.setContentAreaFilled(false);
        leftDoorClosedButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leftDoorClosedButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        leftDoorClosedButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        leftDoorClosedButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        leftDoorClosedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDoorClosedButtonActionPerformed(evt);
            }
        });

        RightDoors.add(rightDoorClosedButton);
        rightDoorClosedButton.setSelected(true);
        rightDoorClosedButton.setText("Closed");
        rightDoorClosedButton.setContentAreaFilled(false);
        rightDoorClosedButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rightDoorClosedButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rightDoorClosedButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        rightDoorClosedButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rightDoorClosedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightDoorClosedButtonActionPerformed(evt);
            }
        });

        Heater.add(heaterOnButton);
        heaterOnButton.setText(" On ");
        heaterOnButton.setContentAreaFilled(false);
        heaterOnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        heaterOnButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        heaterOnButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        heaterOnButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        heaterOnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heaterOnButtonActionPerformed(evt);
            }
        });

        AC.add(acOnButton);
        acOnButton.setText(" On ");
        acOnButton.setContentAreaFilled(false);
        acOnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        acOnButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        acOnButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        acOnButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        acOnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acOnButtonActionPerformed(evt);
            }
        });

        Lights.add(lightsOnButton);
        lightsOnButton.setText(" On ");
        lightsOnButton.setContentAreaFilled(false);
        lightsOnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lightsOnButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lightsOnButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lightsOnButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lightsOnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightsOnButtonActionPerformed(evt);
            }
        });

        AC.add(acOffButton);
        acOffButton.setSelected(true);
        acOffButton.setText(" Off  ");
        acOffButton.setContentAreaFilled(false);
        acOffButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        acOffButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        acOffButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        acOffButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        acOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acOffButtonActionPerformed(evt);
            }
        });

        Lights.add(lightsOffButton);
        lightsOffButton.setSelected(true);
        lightsOffButton.setText(" Off  ");
        lightsOffButton.setContentAreaFilled(false);
        lightsOffButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lightsOffButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lightsOffButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lightsOffButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lightsOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightsOffButtonActionPerformed(evt);
            }
        });

        LeftDoors.add(leftDoorFailButton);
        leftDoorFailButton.setText("Fail");
        leftDoorFailButton.setContentAreaFilled(false);
        leftDoorFailButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leftDoorFailButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        leftDoorFailButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        leftDoorFailButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        leftDoorFailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDoorFailButtonActionPerformed(evt);
            }
        });

        AC.add(acFailButton);
        acFailButton.setText("Fail");
        acFailButton.setContentAreaFilled(false);
        acFailButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        acFailButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        acFailButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        acFailButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        acFailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acFailButtonActionPerformed(evt);
            }
        });

        Heater.add(heaterFailButton);
        heaterFailButton.setText("Fail");
        heaterFailButton.setContentAreaFilled(false);
        heaterFailButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        heaterFailButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        heaterFailButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        heaterFailButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        heaterFailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heaterFailButtonActionPerformed(evt);
            }
        });

        RightDoors.add(rightDoorFailButton);
        rightDoorFailButton.setText("Fail");
        rightDoorFailButton.setContentAreaFilled(false);
        rightDoorFailButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rightDoorFailButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rightDoorFailButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        rightDoorFailButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rightDoorFailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightDoorFailButtonActionPerformed(evt);
            }
        });

        Lights.add(lightsFailButton);
        lightsFailButton.setText("Fail");
        lightsFailButton.setContentAreaFilled(false);
        lightsFailButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lightsFailButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lightsFailButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lightsFailButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lightsFailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightsFailButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Lights");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("AC");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Heater");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Left Doors");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Right Doors");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Vehicle");

        adButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adButton.setText("Advertise");
        adButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adButtonActionPerformed(evt);
            }
        });

        autoButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        autoButton.setText("Automatic");
        autoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoButtonActionPerformed(evt);
            }
        });

        vParamButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vParamButton.setText("Vehicle Parameters");
        vParamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vParamButtonActionPerformed(evt);
            }
        });

        trainIDFld.setEditable(false);
        trainIDFld.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        trainIDFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        trainIDFld.setText(Integer.toString(tv.tm.ID));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Train ID");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lightsOnButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lightsOffButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lightsFailButton))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(heaterOnButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(heaterOffButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(heaterFailButton)
                                        .addGap(2, 2, 2))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(acOnButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(acOffButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(acFailButton))))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(rightDoorOpenButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rightDoorClosedButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rightDoorFailButton))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(leftDoorOpenButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(leftDoorClosedButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(leftDoorFailButton))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(autoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vParamButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(trainIDFld, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lightsOnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lightsOffButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lightsFailButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acOffButton)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(acOnButton)
                                .addComponent(acFailButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(heaterOnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(heaterOffButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(heaterFailButton))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(leftDoorClosedButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leftDoorOpenButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leftDoorFailButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rightDoorFailButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rightDoorOpenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rightDoorClosedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(trainIDFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(autoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(adButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vParamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Motion");

        setSpdFld.setEditable(false);
        setSpdFld.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        setSpdFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        setSpdFld.setText(Integer.toString(tv.tm.setpnt));
        setSpdFld.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                setSpdFldInputMethodTextChanged(evt);
            }
        });
        setSpdFld.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                setSpdFldPropertyChange(evt);
            }
        });

        authFld.setEditable(false);
        authFld.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        authFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        authFld.setText(Integer.toString(tv.tm.authority));
        authFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authFldActionPerformed(evt);
            }
        });

        curSpdFld.setEditable(false);
        curSpdFld.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        curSpdFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        curSpdFld.setText(Integer.toString(tv.tm.curSpd));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Current Speed (mph)");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Setpoint Speed (mph)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Power Request (MW)");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Speed Request (mph)");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jSlider1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        psngrBrkButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        psngrBrkButton.setForeground(new java.awt.Color(255, 0, 0));
        psngrBrkButton.setText("Passenger Brake");
        psngrBrkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psngrBrkButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Authority (mi)");

        pwrReqFld.setEditable(false);
        pwrReqFld.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pwrReqFld.setForeground(new java.awt.Color(0, 0, 250));
        pwrReqFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwrReqFld.setText(Integer.toString(tv.tm.powReq));
        pwrReqFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwrReqFldActionPerformed(evt);
            }
        });

        spdReqFld.setEditable(false);
        spdReqFld.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        spdReqFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        spdReqFld.setText(Integer.toString(tv.tm.spdReq));

        eBrkButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eBrkButton.setForeground(new java.awt.Color(255, 0, 0));
        eBrkButton.setText("Emergency Stop");
        eBrkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBrkButtonActionPerformed(evt);
            }
        });

        srvBrkButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        srvBrkButton.setForeground(new java.awt.Color(255, 0, 0));
        srvBrkButton.setText("Service Brake");
        srvBrkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srvBrkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(srvBrkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(psngrBrkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(eBrkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spdReqFld)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pwrReqFld)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(curSpdFld, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(authFld, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(setSpdFld)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spdReqFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwrReqFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setSpdFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(psngrBrkButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(srvBrkButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(7, 7, 7)
                        .addComponent(eBrkButton))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(curSpdFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(30, 30, 30)
                        .addComponent(authFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addGap(43, 43, 43))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Train Controller");

        console.setEditable(false);
        console.setColumns(20);
        console.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        console.setRows(5);
        jScrollPane1.setViewportView(console);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(407, 407, 407))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
		this.setVisible(true);
    }// </editor-fold>                        

    private void authFldActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                                                                   

    private void pwrReqFldActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void vParamButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
		console.append(tv.tm.getVehicleParam());
    }                                        

    private void autoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        tv.tm.setAuto(autoButton.isSelected());
		console.append("Automatic mode: " + tv.tm.auto + "\n");
    }                                              

    private void adButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        tv.tm.setAd(adButton.isSelected());
		console.append("Advertisement: " + tv.tm.ad + "\n");
    }                                        

    private void psngrBrkButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        tv.tm.setPsngrBrk(psngrBrkButton.isSelected());
		console.append("Passenger brake: " + tv.tm.psngrBrk + "\n");
    }                                             

	private void lightsOnButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
		tv.tm.setLights(1);
		console.append("Lights state: " + tv.tm.lights + "\n");
    }  	
	private void lightsOffButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
		tv.tm.setLights(2);
		console.append("Lights state: " + tv.tm.lights + "\n");
    } 
	private void lightsFailButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
		tv.tm.setLights(3);
		console.append("Lights state: " + tv.tm.lights + "\n");
    }
	
	private void acOnButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        tv.tm.setAC(1);
		console.append("AC state: " + tv.tm.ac + "\n");
    }
	private void acOffButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
		tv.tm.setAC(2);
		console.append("AC state: " + tv.tm.ac + "\n");
    } 
	private void acFailButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
		tv.tm.setAC(3);
		console.append("AC state: " + tv.tm.ac + "\n");
    } 
	
    
    private void heaterOnButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
		tv.tm.setHeat(1);
		console.append("Heater state: " + tv.tm.heater+ "\n");
    }	
	private void heaterOffButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
		tv.tm.setHeat(2);
		console.append("Heater state: " + tv.tm.heater + "\n");
    } 
	private void heaterFailButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
		tv.tm.setHeat(3);
		console.append("Heater state: " + tv.tm.heater + "\n");
    }
	
	private void leftDoorOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
		tv.tm.setLDoor(1);
		console.append("Left door state: " + tv.tm.leftDoors + "\n");
    } 
	private void leftDoorClosedButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
		tv.tm.setLDoor(2);
		console.append("Left door state: " + tv.tm.leftDoors + "\n");
    }
    private void leftDoorFailButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
		tv.tm.setLDoor(3);
		console.append("Left door state: " + tv.tm.leftDoors + "\n");
    }   

    private void rightDoorOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
		tv.tm.setRDoor(1);
		console.append("Right door state: " + tv.tm.rightDoors + "\n");
    }  
	private void rightDoorClosedButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
		tv.tm.setRDoor(2);
		console.append("Right door state: " + tv.tm.rightDoors + "\n");
    } 	
	private void rightDoorFailButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
		tv.tm.setRDoor(3);
		console.append("Right door state: " + tv.tm.rightDoors + "\n");
    }  

    
	
	

    private void jSlider1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void setSpdFldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {                                      
        float spdReq =  jSlider1.getValue(); //pull value from the controller
        spdReq = spdReq/(float)100.0; //convert to percentage
        spdReq = spdReq * tv.tm.maxSpd; //convert to mph from 0-43.5mph
        int intSpdReq = (int) spdReq; ///cast
        spdReqFld.setText(Integer.toString(intSpdReq)); //update GUI

        tv.tm.setSpdReq((int) spdReq);  //call method
    }                                     

    private void setSpdFldPropertyChange(java.beans.PropertyChangeEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void eBrkButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        tv.tm.setEBrk(eBrkButton.isSelected());
		console.append("Emergency Stop: " + tv.tm.eBrk + "\n");
    }                                        

    private void srvBrkButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        tv.tm.setSrvBrk(srvBrkButton.isSelected());
		console.append("Service Brake: " + tv.tm.srvBrk + "\n");
    }                                        

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
        // /* Set the Nimbus look and feel */
        // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         // * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         // */
        // try {
            // for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                // if ("Nimbus".equals(info.getName())) {
                    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    // break;
                // }
            // }
        // } catch (ClassNotFoundException ex) {
            // java.util.logging.Logger.getLogger(TrainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // } catch (InstantiationException ex) {
            // java.util.logging.Logger.getLogger(TrainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // } catch (IllegalAccessException ex) {
            // java.util.logging.Logger.getLogger(TrainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            // java.util.logging.Logger.getLogger(TrainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // }
        // //</editor-fold>

        // /* Create and display the form */
        // java.awt.EventQueue.invokeLater(new Runnable() {
            // public void run() {
                // new TrainController().setVisible(true);
            // }
        // });
    // }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup AC;
    private javax.swing.ButtonGroup Heater;
    private javax.swing.ButtonGroup LeftDoors;
    private javax.swing.ButtonGroup Lights;
    private javax.swing.ButtonGroup RightDoors;
    private javax.swing.JToggleButton psngrBrkButton;
    private javax.swing.JToggleButton eBrkButton;
    private javax.swing.JToggleButton adButton;
    private javax.swing.JButton vParamButton;
    private javax.swing.JToggleButton srvBrkButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton acOnButton;
    private javax.swing.JRadioButton rightDoorClosedButton;
    private javax.swing.JRadioButton lightsOnButton;
    private javax.swing.JRadioButton acOffButton;
    private javax.swing.JRadioButton lightsOffButton;
    private javax.swing.JRadioButton leftDoorFailButton;
    private javax.swing.JRadioButton acFailButton;
    private javax.swing.JRadioButton heaterFailButton;
    private javax.swing.JRadioButton rightDoorFailButton;
    private javax.swing.JRadioButton lightsFailButton;
    private javax.swing.JRadioButton leftDoorOpenButton;
    private javax.swing.JRadioButton rightDoorOpenButton;
    private javax.swing.JRadioButton heaterOffButton;
    private javax.swing.JRadioButton leftDoorClosedButton;
    private javax.swing.JRadioButton heaterOnButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea console;
    private javax.swing.JTextField setSpdFld;
    private javax.swing.JTextField authFld;
    private javax.swing.JTextField curSpdFld;
    private javax.swing.JTextField pwrReqFld;
    private javax.swing.JTextField spdReqFld;
    private javax.swing.JTextField trainIDFld;
    private javax.swing.JToggleButton autoButton;
    // End of variables declaration                   
}
