import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

// Note to self:
// When you want to change a train's route, you need to send an array of switchstatesuggestions
// This has train ID, an array of block numbers for switches, and a boolean array of switch states
// So when you get a route change from the user, you have to do the following: Find out which block the train is on
// Find out what switches are on the path and what their switch states need to be in order for it to get there
// Do this by iterating through blocks on the track model (I guess in a for loop)
// Whenever you see a switch look after the blocks after it to the left and the blocks after it on the right
// If you see the block you're looking for on one of the paths, then you make the switch change to that corresponding state
// Since the switch array is unique to each train, you don't have to look at switch states for any other train in order to make this array
/**
 * Throughput statistics (just as a chart) , track failures as a list , button to add/ remove tracks, and button to display train schedule
 * @author admin
 */

public class NewestGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewestGUI
     */
	static ArrayList<Block> RedBlocklist = new ArrayList<Block>();
	static ArrayList<Block> GreenBlocklist = new ArrayList<Block>();
	static ArrayList<Train> Trainlist = new ArrayList<Train>();
	
	static Block NullBlock = new Block();
	static Train NullTrain = new Train();

    public static int hourDepart;
	public int minuteDepart;
	public static int getHourDepart;
	public static boolean Event = false;
	static int trcounter = 0;

    public NewestGUI() {
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
     private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        AMorPMDep = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel16 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SetSwitchonLine = new javax.swing.JComboBox();
        SetSwitchatNum = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        EnableSwitch = new javax.swing.JCheckBox();
        DisableSwitch = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MonitorBlockTable = new javax.swing.JTable();
        MonitorBlockNumber = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        MonitorLine = new javax.swing.JComboBox();
        EnableBlock = new javax.swing.JButton();
        DisableBlock = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SetAuth = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AuthSetatBlock = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        ActuallySetAuth = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CTC Office - Blue Team");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Set Suggestion"));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Shadyside ", "Herron Ave ", "Switchville ", "Penn Station", "First Avenue ", "Station Square ", "South Hills Junction","1","2","3","4","5","6","7","8","9","10" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Destination");

        jLabel2.setText("Hour of departure");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " ", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Minute of departure");
        jLabel3.setToolTipText("");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", " " }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        AMorPMDep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM", " " }));
        AMorPMDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMorPMDepActionPerformed(evt);
            }
        });

        jTextField1.setText("10");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setText("mi - Authority");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AMorPMDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 149, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AMorPMDep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4)
                .addComponent(jButton1))
        );

        jScrollPane2.setMaximumSize(new java.awt.Dimension(32600, 31000));

        jLabel16.setIcon(new javax.swing.ImageIcon("1186traindiagram.png")); // NOI18N
        jScrollPane2.setViewportView(jLabel16);

        jLabel17.setText("Simulation Speed");

        jLabel18.setText("1x");

        jLabel19.setText("10x");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Set Switches"));

        SetSwitchonLine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Red", "Green" }));
        SetSwitchonLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetSwitchonLineActionPerformed(evt);
            }
        });

        SetSwitchatNum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", " ", " " }));
        SetSwitchatNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetSwitchatNumActionPerformed(evt);
            }
        });

        jLabel7.setText("Switch #");

        buttonGroup10.add(EnableSwitch);
        EnableSwitch.setText("Enable");
        EnableSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnableSwitchActionPerformed(evt);
            }
        });

        buttonGroup10.add(DisableSwitch);
        DisableSwitch.setText("Disable");
        DisableSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisableSwitchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisableSwitch)
                    .addComponent(EnableSwitch)
                    .addComponent(SetSwitchonLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(SetSwitchatNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(SetSwitchonLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SetSwitchatNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(EnableSwitch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisableSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Current Speed - 5x");
		MonitorBlockTable.setFont(new java.awt.Font("Tahoma", 0, 18));
        MonitorBlockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Block #", "Status", "Occupied"
            }
        ));
        MonitorBlockTable.setRowHeight(32);
        jScrollPane3.setViewportView(MonitorBlockTable);

        MonitorBlockNumber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", " ", " " }));
        MonitorBlockNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonitorBlockNumberActionPerformed(evt);
            }
        });

        jLabel5.setText("Block #");

        MonitorLine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Red", "Green" }));
        MonitorLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonitorLineActionPerformed(evt);
            }
        });

        EnableBlock.setText("Enable");
        EnableBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnableBlockActionPerformed(evt);
            }
        });

        DisableBlock.setText("Disable");
        DisableBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisableBlockActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Train Location", "Speed", "Speed Limit", "Authority"
            }
        ));
        jTable1.setRowHeight(32);
        jScrollPane1.setViewportView(jTable1);

        SetAuth.setText("10");

        jLabel8.setText("mi");

        AuthSetatBlock.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", " ", " " }));
        AuthSetatBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthSetatBlockActionPerformed(evt);
            }
        });

        jLabel9.setText("Block # of train");

        ActuallySetAuth.setText("Set Authority");
        ActuallySetAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActuallySetAuthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(43, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(MonitorBlockNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(MonitorLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EnableBlock)
                                        .addGap(32, 32, 32)
                                        .addComponent(DisableBlock))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19))
                                    .addComponent(jSlider1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel17))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ActuallySetAuth)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SetAuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(AuthSetatBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(MonitorBlockNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MonitorLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnableBlock)
                            .addComponent(DisableBlock))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SetAuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(AuthSetatBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ActuallySetAuth)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        // This is the hour of departure
        String time = (String)jComboBox2.getSelectedItem();
        hourDepart = atoi(time);
    }                                          

    private void AMorPMDepActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        // This is the send button
		String time = (String)jComboBox2.getSelectedItem();
        hourDepart = atoi(time);
		time = (String)jComboBox3.getSelectedItem();
		minuteDepart = atoi(time);
		String AM = (String)AMorPMDep.getSelectedItem();
		String destination =(String)jComboBox1.getSelectedItem();
		int authority = Integer.parseInt(jTextField1.getText());
		System.out.print("The train departs at " + hourDepart + ":" + minuteDepart + " " + AM + " for " + destination + "\n"  );
		System.out.println("It has an authority of " + authority + " miles.");
		
		//Take the string of the destination and transform it into the appropriate integer
		//Figure out using the track model class whether it is a red line or a green line block
		//Start from the block right in front of the yard, do a linear search for the destination
		//If you hit a switch, do a linear search for each path until you hit the part where they merge again
		//If you find the destination on that linear search, then record that switch state and make it essential
		//If you do not, keep going!
		//Once you find the destination, you should have been keeping a tally of the entire distance it took to get to that point
		//Send this in as the authority, and take the authority and divide it by the current time to get the average speed that the train should go at
		//Now you just wait for a rejection or acceptance (via track circuit notification)
		
		
		
    }                                        

    private void MonitorBlockNumberActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
		int blocknumber = atoi((String)(MonitorBlockNumber.getSelectedItem()));
		DefaultTableModel model = (DefaultTableModel)MonitorBlockTable.getModel();
		model.setValueAt(blocknumber,0,0);
		
    }                                                  

    private void MonitorLineActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
		DefaultTableModel model = (DefaultTableModel)MonitorBlockTable.getModel();
		int blocknumber = atoi((String)(MonitorBlockNumber.getSelectedItem()));
		String line = (String)MonitorLine.getSelectedItem();
		Block tempBlock = new Block();
		if(line.equals("Green"))
		{
			tempBlock = GreenBlocklist.get(blocknumber);
			model.setValueAt(tempBlock.blockNumber,0,0);
			model.setValueAt(tempBlock.status,0,1);
			if(tempBlock.Occup)
			{
				model.setValueAt("True",0,2);
				
			}
			else
			{
				model.setValueAt("False",0,2);
			}
		}
		if(line.equals("Red"))
		{
			tempBlock = RedBlocklist.get(blocknumber);
			model.setValueAt(tempBlock.blockNumber,0,0);
			model.setValueAt(tempBlock.status,0,1);
			if(tempBlock.Occup)
			{
				model.setValueAt("True",0,2);
				
			}
			else
			{
				model.setValueAt("False",0,2);
			}
			
		}
		}                                           

    private void EnableBlockActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
		int blocknumber = atoi((String)(MonitorBlockNumber.getSelectedItem()));
		System.out.println("Block "+blocknumber + " has been enabled.");
    }                                           

    private void DisableBlockActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
		int blocknumber = atoi((String)(MonitorBlockNumber.getSelectedItem()));
		System.out.println("Block "+blocknumber + " has been disabled.");
    }                                            

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void SetSwitchonLineActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void SetSwitchatNumActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void DisableSwitchActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:		String currline = SetSwitchonLine.getSelectedItem();
		String currBlock = (String)SetSwitchatNum.getSelectedItem();
		String currline = (String)SetSwitchonLine.getSelectedItem();
		System.out.println("You have disabled switch number "+currBlock+" on the " + currline + " line.");
    }                                             

    private void EnableSwitchActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
		String currline = (String)SetSwitchonLine.getSelectedItem();
		String currBlock = (String)SetSwitchatNum.getSelectedItem();
		System.out.println("You have enabled switch number "+currBlock+" on the " + currline + " line.");
    }                                            

    private void AuthSetatBlockActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void ActuallySetAuthActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
		DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
		int authority = Integer.parseInt(SetAuth.getText());
		String block = (String)AuthSetatBlock.getSelectedItem();
        int blocknum = atoi(block);
		System.out.println("Requested block #" + blocknum);
		boolean success=false;
		for(int i = 0 ; i<5 ; i++)
		{

		    if(blocknum == Trainlist.get(i).trainlocation)
			{
				model.setValueAt(authority,i,3);
				Trainlist.get(i).authority = authority;
				success = true;
				
			}
			if(i == 4 && blocknum != Trainlist.get(i).trainlocation && !success)
			{
				System.out.println("There is no train at this block.");
			}
			
		}
		
    }                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewestGUI().setVisible(true);
            }
        });
		
		for(int i = 0; i <120 ; i++)
		{
			RedBlocklist.add(NullBlock);
			GreenBlocklist.add(NullBlock);
		}
		for(int i = 0; i <10 ; i++)
		{
			Trainlist.add(NullTrain);
			
		}
		while(true)
		{
			
			String s = "";
			//System.out.println("What up homie");
			try{
			s = br.readLine();
			}
			catch(IOException e)
			{}
			
			if(s.equals("Input"))
			{
				System.out.println("Now expecting input");

				int inputchoice = 1;
				try{
				inputchoice = Integer.parseInt(br.readLine());
				}
				catch(IOException e)
				{}
				
				if(inputchoice == 1)
				{
					
					int linechoice=1;
					int blocknumber=1; // This is the block number lmao
					int occupieds=1;
					boolean occupied=false;
					String localstatus = "";
					Block tempBlock = new Block();
					System.out.println("Enter 1 for red or 2 for green");
					try{
					linechoice = Integer.parseInt(br.readLine());
					}
				    catch(IOException e)
					{}
					System.out.println("Enter the block number");
					try{
					blocknumber = Integer.parseInt(br.readLine());
					}
				    catch(IOException e)
					{}
					System.out.println("Enter the occupation status");
					try{
					occupieds = Integer.parseInt(br.readLine());
					}
				    catch(IOException e)
					{}
					if(occupieds==1)
					{
						occupied=true;
					}
					if(occupieds==0)
					{
						occupied=false;
					}
					System.out.println("Enter the status of the block");
					
					localstatus = System.console().readLine();
					
					
					tempBlock.blockNumber = blocknumber;
					tempBlock.status = localstatus;
					tempBlock.line = linechoice;
					tempBlock.Occup = occupied;
					if(tempBlock.line == 1)
					{
						RedBlocklist.set(tempBlock.blockNumber,tempBlock);
					}
					if(tempBlock.line == 2)
					{
						GreenBlocklist.set(tempBlock.blockNumber, tempBlock);
					}
				}
				if(inputchoice == 2)
				{
					int trainlocation=0;
					int speed=0;
					int speedlim=0;
					int authority=0;
					Train tempTrain = new Train();
					System.out.println("Enter the location of the train");
					try{
					trainlocation = Integer.parseInt(br.readLine());
					}
				    catch(IOException e)
					{}
					System.out.println("Enter the current speed of that train");
					try{
					speed = Integer.parseInt(br.readLine());
					}
					catch(IOException e)
					{}
					System.out.println("Enter the current speed limit of that train");
					try{
					speedlim = Integer.parseInt(br.readLine());
					}
					catch(IOException e)
					{}
					System.out.println("Enter the current authority of that train");
					try{
					authority = Integer.parseInt(br.readLine());
					}
					catch(IOException e)
					{}
					tempTrain.trainlocation = trainlocation;
					tempTrain.speed = speed;
					tempTrain.speedlim = speedlim;
					tempTrain.authority = authority;
					
					Trainlist.set(trcounter,tempTrain);
					DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
					
					model.setValueAt(tempTrain.trainlocation,trcounter,0);
					model.setValueAt(tempTrain.speed,trcounter,1);
					model.setValueAt(tempTrain.speedlim,trcounter,2);
					model.setValueAt(tempTrain.authority,trcounter,3);
					trcounter++;
					
					
				}
			}
					
		}
    
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox AMorPMDep;
    private javax.swing.JButton ActuallySetAuth;
    private javax.swing.JComboBox AuthSetatBlock;
    private javax.swing.JButton DisableBlock;
    private javax.swing.JCheckBox DisableSwitch;
    private javax.swing.JButton EnableBlock;
    private javax.swing.JCheckBox EnableSwitch;
    private javax.swing.JComboBox MonitorBlockNumber;
    private javax.swing.JTable MonitorBlockTable;
    private javax.swing.JComboBox MonitorLine;
    private javax.swing.JTextField SetAuth;
    private javax.swing.JComboBox SetSwitchatNum;
    private javax.swing.JComboBox SetSwitchonLine;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration              
    // End of variables declaration                   
	public int atoi(String str) {
	if (str == null || str.length() < 1)
		return 0;
 
	// trim white spaces
	str = str.trim();
 
	char flag = '+';
 
	// check negative or positive
	int i = 0;
	if (str.charAt(0) == '-') {
		flag = '-';
		i++;
	} else if (str.charAt(0) == '+') {
		i++;
	}
	// use double to store result
	double result = 0;
 
	// calculate value
	while (str.length() > i && str.charAt(i) >= '0' && str.charAt(i) <= '9') {
		result = result * 10 + (str.charAt(i) - '0');
		i++;
	}
 
	if (flag == '-')
		result = -result;
 
	// handle max and min
	if (result > Integer.MAX_VALUE)
		return Integer.MAX_VALUE;
 
	if (result < Integer.MIN_VALUE)
		return Integer.MIN_VALUE;
 
	return (int) result;
}

public int getHourDepart()
{
    return hourDepart; 
}

}