@echo off
echo North Shore Extension Installer
echo Compiling TrainModel...
javac TrainModel/*.java
echo Compiling TrainController...
javac -cp "./TrainModel" TrainController/*.java
echo Compiling TrackModel...
javac -cp "./TrainController" TrackModel/*.java
echo Compiling WaysideController...
javac -cp "./TrackModel;./CTCOffice" WaysideController/*.java
echo Compiling CTCOffice...
javac -cp "./TrackModel;./WaysideController" CTCOffice/*.java
pause
echo Launching System
java -cp "./CTCOffice;./WaysideController;./TrackModel;./TrainController;./TrainModel" NSE
pause